name: intl_converter
description: A library tool that help you manager i18n strings in flutter,include convert from android "strings-xx.xml".
version: 0.0.4+3
author: iflutter team <shenkaige86@gmail.com>
homepage: https://github.com/iflutter/intl_converter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  intl_generator: ^0.2.0+0
  xml: ^5.2.0
#  xml: 4.5.1
  args: ^2.2.0
#  shell: ^1.0.1
#  shell:
#    git:
#      url: https://github.com/JellyO1/shell
  #  string_unescape: ^1.5.1
  string_unescape:
    git:
      url: https://github.com/uttusharma/string_unescape
  path: ^1.8.0
dependency_overrides:
  meta: ^1.3.0
#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter: